### ISSUE TITLE
Create new order with type='stopLimit' returns 'code': 2022, 'message': 'Bad price'

### ISSUE THREAD

**Issue by maxreis86** [hitbtc-com/hitbtc-api#241]
Hi guys,

I am trying to place a stopLimit order using the code below, but I got the error 'Bad price'.
Everything was working perfectly and the error started this mornning with exacectely the same code.
Something has been changed in the rest api. Can anyone help me please?

Python code:

import requests
orderData = {'symbol':'BTCUSD', 'side': 'buy', 'type': 'stopLimit', 'quantity': '0.002', 'price': '8317.18', 'stopPrice': '8317.18'}
r = requests.post('https://api.hitbtc.com/api/2/order', data = orderData, auth=('yyyy', 'xxxx'))
print(r.json())

ERROR:
{'error': {'code': 2022, 'message': 'Bad price'}}

Thank you guys!!

**Comment by svanas** [comment]
Confirmed. I am seeing the same error as a response to https://api.hitbtc.com/api/2/order trying to place a stop-loss order. Both `stopLimit` and `stopMarket` seem to be having this problem.

**Comment by svanas** [comment]
[Docs](https://api.hitbtc.com/#errors) tell us about `2022/Bad price`: "See more details in error description field"

`{"error":{"code":2022,"message":"Bad price"}}`

Right.

**Comment by hitbtc-com** [comment]
Thank you, for your bug report. 
Bug is fixed.

**Comment by svanas** [comment]
@hitbtc-com when will you deploy the fix? we are still receiving `Bad price` errors (or `Price is not a valid number` when we place a `stopMarket` order without a `price`)

**Comment by hitbtc-com** [comment]
Now really fixed.
Thanks for the detailed bug report.
